---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - loki-minio-secret.yaml
  - loki.yaml
  - kube-prometheus-stack.yaml
  - jaeger.yaml
  - opentelemetry-operator.yaml
  - reloader.yaml
  - boinc.yaml
