---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - loki.yaml
  - kube-prometheus-stack.yaml
  - jaeger.yaml
  - opentelemetry-operator.yaml
  - reloader.yaml
  - media-mounts.yaml
  - bjw-s-labs-repo.yaml
  - sabnzbd.yaml
  - sonarr.yaml
  - radarr.yaml
  - prowlarr.yaml
  - overseerr.yaml
