apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:nS6Y7LqUfkkx6r2FhojCiTtqqjJK2tsb2BgJvaYvWdxSB5zdAcollQ==,iv:AkhWQ9IOauO9sR1+fpFgfF5sZ0X6vH/wNYwrPXXIuso=,tag:8KwzhGQuQzDybMRBxXsBcw==,type:str]
sops:
    age:
        - recipient: age1hvmdhkt8llkq3m00ullewwgycy2ujr8tlhqk6ley07usyexcq9vsz8mymh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUUxHQkNIQklIQll2bzBr
            WGMranRpTCt0TWdheTBjUW1lNjJEbmtPV21VCmxkVHJ3UndsNHVoeUkvZXUvdnNJ
            aHdDcjBGZ2pHOHhTb2l6aUVCOWlFek0KLS0tIE1GOGo0ZXorRGg5WVl5NmMvUTdG
            SUVVd2FXVlRkWjhCMVlDSjkvR2prNEkKzvfEtZN4bjBdJn+kHk530OsOFEFJfqeh
            dqz6qT5mQe4H8dYKejgzVSiOOxyhYsdVqlV2Of0zrkJo+52A3VxsZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T12:57:51Z"
    mac: ENC[AES256_GCM,data:8SUyGCP8P6HeBiaFUGila4HVZWvo30NLD1D3QsKnUaCCv0cUBxFqGrpxiFdncSLAvoFho3dhGggMjBHD1Bu9a28OCFydPy8ii3UEm0azLHpDvL6AS8E3/EkQAW2hVs3Wd6PVTx0d17/dTgGvAyNKg3+u+BjraVApdCMe0tiSORc=,iv:w20TpVCkX2ZqEEp8JLVlb8jaoRStCvSZ7IixyvmEUzM=,tag:uxlsrlx5qZ0F1EXDgzFeCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
