---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - cloudflare-secret.yaml
  - cluster-issuers.yaml
  - traefik-tls.yaml
  - monitoring-tls.yaml
  - metallb.yaml
  - traefik-secret.yaml
  - discord-secret.yaml
